//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace confocal_core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float FullScanRange {
            get {
                return ((float)(this["FullScanRange"]));
            }
            set {
                this["FullScanRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AcquisitionMode {
            get {
                return ((int)(this["AcquisitionMode"]));
            }
            set {
                this["AcquisitionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScannerHead {
            get {
                return ((int)(this["ScannerHead"]));
            }
            set {
                this["ScannerHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScanDirection {
            get {
                return ((int)(this["ScanDirection"]));
            }
            set {
                this["ScanDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScanMode {
            get {
                return ((int)(this["ScanMode"]));
            }
            set {
                this["ScanMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ScanPixel {
            get {
                return ((int)(this["ScanPixel"]));
            }
            set {
                this["ScanPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ScanPixelDwell {
            get {
                return ((int)(this["ScanPixelDwell"]));
            }
            set {
                this["ScanPixelDwell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FastModeEnabled {
            get {
                return ((bool)(this["FastModeEnabled"]));
            }
            set {
                this["FastModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanLineSkipEnabled {
            get {
                return ((bool)(this["ScanLineSkipEnabled"]));
            }
            set {
                this["ScanLineSkipEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScanLineSkip {
            get {
                return ((int)(this["ScanLineSkip"]));
            }
            set {
                this["ScanLineSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double ScanChannel405LaserPower {
            get {
                return ((double)(this["ScanChannel405LaserPower"]));
            }
            set {
                this["ScanChannel405LaserPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumPurple")]
        public global::System.Drawing.Color ScanChannel405LaserColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel405LaserColor"]));
            }
            set {
                this["ScanChannel405LaserColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanChannel405Activated {
            get {
                return ((bool)(this["ScanChannel405Activated"]));
            }
            set {
                this["ScanChannel405Activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ScanChannel405Gain {
            get {
                return ((int)(this["ScanChannel405Gain"]));
            }
            set {
                this["ScanChannel405Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScanChannel405Offset {
            get {
                return ((int)(this["ScanChannel405Offset"]));
            }
            set {
                this["ScanChannel405Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ScanChannel405Gamma {
            get {
                return ((int)(this["ScanChannel405Gamma"]));
            }
            set {
                this["ScanChannel405Gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumPurple")]
        public global::System.Drawing.Color ScanChannel405PseudoColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel405PseudoColor"]));
            }
            set {
                this["ScanChannel405PseudoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double ScanChannel488LaserPower {
            get {
                return ((double)(this["ScanChannel488LaserPower"]));
            }
            set {
                this["ScanChannel488LaserPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkCyan")]
        public global::System.Drawing.Color ScanChannel488LaserColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel488LaserColor"]));
            }
            set {
                this["ScanChannel488LaserColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanChannel488Activated {
            get {
                return ((bool)(this["ScanChannel488Activated"]));
            }
            set {
                this["ScanChannel488Activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ScanChannel488Gain {
            get {
                return ((int)(this["ScanChannel488Gain"]));
            }
            set {
                this["ScanChannel488Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScanChannel488Offset {
            get {
                return ((int)(this["ScanChannel488Offset"]));
            }
            set {
                this["ScanChannel488Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ScanChannel488Gamma {
            get {
                return ((int)(this["ScanChannel488Gamma"]));
            }
            set {
                this["ScanChannel488Gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkCyan")]
        public global::System.Drawing.Color ScanChannel488PseudoColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel488PseudoColor"]));
            }
            set {
                this["ScanChannel488PseudoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double ScanChannel561LaserPower {
            get {
                return ((double)(this["ScanChannel561LaserPower"]));
            }
            set {
                this["ScanChannel561LaserPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YellowGreen")]
        public global::System.Drawing.Color ScanChannel561LaserColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel561LaserColor"]));
            }
            set {
                this["ScanChannel561LaserColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanChannel561Activated {
            get {
                return ((bool)(this["ScanChannel561Activated"]));
            }
            set {
                this["ScanChannel561Activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ScanChannel561Gain {
            get {
                return ((int)(this["ScanChannel561Gain"]));
            }
            set {
                this["ScanChannel561Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScanChannel561Offset {
            get {
                return ((int)(this["ScanChannel561Offset"]));
            }
            set {
                this["ScanChannel561Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ScanChannel561Gamma {
            get {
                return ((int)(this["ScanChannel561Gamma"]));
            }
            set {
                this["ScanChannel561Gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YellowGreen")]
        public global::System.Drawing.Color ScanChannel561PseudoColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel561PseudoColor"]));
            }
            set {
                this["ScanChannel561PseudoColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ScanChannel640LaserPower {
            get {
                return ((double)(this["ScanChannel640LaserPower"]));
            }
            set {
                this["ScanChannel640LaserPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumVioletRed")]
        public global::System.Drawing.Color ScanChannel640LaserColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel640LaserColor"]));
            }
            set {
                this["ScanChannel640LaserColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScanChannel640Activated {
            get {
                return ((bool)(this["ScanChannel640Activated"]));
            }
            set {
                this["ScanChannel640Activated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ScanChannel640Gain {
            get {
                return ((int)(this["ScanChannel640Gain"]));
            }
            set {
                this["ScanChannel640Gain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ScanChannel640Offset {
            get {
                return ((int)(this["ScanChannel640Offset"]));
            }
            set {
                this["ScanChannel640Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int ScanChannel640Gamma {
            get {
                return ((int)(this["ScanChannel640Gamma"]));
            }
            set {
                this["ScanChannel640Gamma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumVioletRed")]
        public global::System.Drawing.Color ScanChannel640PseudoColor {
            get {
                return ((global::System.Drawing.Color)(this["ScanChannel640PseudoColor"]));
            }
            set {
                this["ScanChannel640PseudoColor"] = value;
            }
        }
    }
}
